---
apiVersion: v1
kind: ReplicationController
metadata:
  name: myrc
spec:
  replicas: 2
  selector:
    app: medical

  template:
    metadata:
      labels:
        app: medical
    spec:
      containers:
        - name: medical-cont
          image: aarushtechnologies/medical
          ports:
            - containerPort: 80
